# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest2():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test2(self):
    self.driver.get("https://okko.tv/movie/taxi-975070")
    self.driver.set_window_size(962, 693)
    self.driver.find_element(By.CSS_SELECTOR, ".FtMhtc4s .\\_9vY2xAN").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    element = self.driver.find_element(By.CSS_SELECTOR, ".zUEZkIiY")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".zUEZkIiY svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".zUEZkIiY svg").click()
    self.driver.find_element(By.CSS_SELECTOR, ".h2hfN1w1 > .b_O0enV_").click()
    self.driver.find_element(By.CSS_SELECTOR, ".h2hfN1w1 > .b_O0enV_").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".h2hfN1w1 > .b_O0enV_")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".\\__8cp28QVr svg").click()
    self.driver.execute_script("window.scrollTo(0,422.3999938964844)")
  
