# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://okko.tv/movie/fight-club")
    self.driver.set_window_size(683, 824)
    self.driver.find_element(By.CSS_SELECTOR, ".MbmjcbEA:nth-child(2) .\\_9vY2xAN").click()
    self.driver.find_element(By.CSS_SELECTOR, ".MbmjcbEA:nth-child(2) .\\_9vY2xAN").click()
    self.driver.find_element(By.CSS_SELECTOR, ".\\__9Iww5cH_ .Vply81jm").click()
    element = self.driver.find_element(By.CSS_SELECTOR, ".\\__9Iww5cH_ .Vply81jm")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, ".eM4Ndc70:nth-child(9) > .cO_8eiNN > span").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fLAz9yTN:nth-child(1) span").click()
  
